/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#ffffff',
        'surface-dim': '#f8fafc',
        'surface-bright': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f8fafc',
        'surface-container': '#f1f5f9',
        'surface-container-high': '#e2e8f0',
        'surface-container-highest': '#cbd5e1',
        'on-surface': '#0f172a',
        'on-surface-variant': '#475569',
        'inverse-surface': '#1e293b',
        'inverse-on-surface': '#f1f5f9',
        outline: '#94a3b8',
        'outline-variant': '#cbd5e1',
        'surface-tint': '#2563eb',
        primary: '#2563eb',
        'on-primary': '#ffffff',
        'primary-container': '#dbeafe',
        'on-primary-container': '#1e3a8a',
        'inverse-primary': '#60a5fa',
        secondary: '#6366f1',
        'on-secondary': '#ffffff',
        'secondary-container': '#e0e7ff',
        'on-secondary-container': '#312e81',
        tertiary: '#0ea5e9',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#e0f2fe',
        'on-tertiary-container': '#0c4a6e',
        error: '#ef4444',
        'on-error': '#ffffff',
        'error-container': '#fee2e2',
        'on-error-container': '#991b1b',
        'primary-fixed': '#dbeafe',
        'primary-fixed-dim': '#bfdbfe',
        'on-primary-fixed': '#1e3a8a',
        'on-primary-fixed-variant': '#1e40af',
        'secondary-fixed': '#e0e7ff',
        'secondary-fixed-dim': '#c7d2fe',
        'on-secondary-fixed': '#312e81',
        'on-secondary-fixed-variant': '#3730a3',
        'tertiary-fixed': '#e0f2fe',
        'tertiary-fixed-dim': '#bae6fd',
        'on-tertiary-fixed': '#0c4a6e',
        'on-tertiary-fixed-variant': '#075985',
        background: '#f0f6ff',
        'on-background': '#0f172a',
        'surface-variant': '#e2e8f0',
        'glass-bg': 'rgba(255, 255, 255, 0.7)',
        'glass-border': 'rgba(255, 255, 255, 0.4)',
      },
      fontFamily: {
        sans: ['Outfit', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      animation: {
        'blob': 'blob 7s infinite',
      },
      keyframes: {
        blob: {
          '0%': {
            transform: 'translate(0px, 0px) scale(1)',
          },
          '33%': {
            transform: 'translate(30px, -50px) scale(1.1)',
          },
          '66%': {
            transform: 'translate(-20px, 20px) scale(0.9)',
          },
          '100%': {
            transform: 'translate(0px, 0px) scale(1)',
          },
        },
      },
    },
  },
  plugins: [],
}
